<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginInvalidCredentials</name>
   <tag></tag>
   <elementGuidId>21bc1dca-cbe8-4ada-9734-54b54b4f0d56</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'LoginInvalid credentialsUsername : AdminPassword : admin123UsernamePassword Login Forgot your password? OrangeHRM OS 5.6.1© 2005 - 2024 OrangeHRM, Inc. All rights reserved.' or . = 'LoginInvalid credentialsUsername : AdminPassword : admin123UsernamePassword Login Forgot your password? OrangeHRM OS 5.6.1© 2005 - 2024 OrangeHRM, Inc. All rights reserved.')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-login-layout-blob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#app div >> internal:has-text=&quot;LoginInvalid credentials&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9dbeb925-022f-44f4-8803-4f793d7789a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-login-layout-blob</value>
      <webElementGuid>d2344868-9f40-480d-98a7-d30deb12d394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginInvalid credentialsUsername : AdminPassword : admin123UsernamePassword Login Forgot your password? OrangeHRM OS 5.6.1© 2005 - 2024 OrangeHRM, Inc. All rights reserved.</value>
      <webElementGuid>544a6106-6928-4c6c-bab2-e333710eba2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;orangehrm-login-layout&quot;]/div[@class=&quot;orangehrm-login-layout-blob&quot;]</value>
      <webElementGuid>cf8d085f-1df9-4847-96a8-38b08870fa8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div</value>
      <webElementGuid>b5ac11a1-3470-45a2-a56d-dec05a564f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>1a31bc2a-7e2d-4ec9-9576-3cbfc46e8799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginInvalid credentialsUsername : AdminPassword : admin123UsernamePassword Login Forgot your password? OrangeHRM OS 5.6.1© 2005 - 2024 OrangeHRM, Inc. All rights reserved.' or . = 'LoginInvalid credentialsUsername : AdminPassword : admin123UsernamePassword Login Forgot your password? OrangeHRM OS 5.6.1© 2005 - 2024 OrangeHRM, Inc. All rights reserved.')]</value>
      <webElementGuid>315fad5f-57ec-40c1-9031-17b1ea35c557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
