<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Current Filedependents.xlsxReplace Wit_7937b0</name>
   <tag></tag>
   <elementGuidId>e85b195e-c482-4e20-b456-eaa37eaf6cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.oxd-form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]/div[5]/div/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Current Filedependents.xlsxReplace WithBrowseNo file selectedAccepts up to 1MBCo&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>7654fb84-4051-42cd-bbdf-1b38592eba9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-form</value>
      <webElementGuid>babf16a7-36f4-4c13-a3b9-9a4ea643b3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Current Filedependents.xlsxReplace WithBrowseNo file selectedAccepts up to 1MBComment * Required Cancel  Save </value>
      <webElementGuid>bd293fa9-0213-4e58-b854-8d7e4be97e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout orangehrm-upgrade-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/div[@class=&quot;orangehrm-edit-employee&quot;]/div[@class=&quot;orangehrm-edit-employee-content&quot;]/div[@class=&quot;orangehrm-attachment&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/form[@class=&quot;oxd-form&quot;]</value>
      <webElementGuid>ba34099b-882e-40bc-937c-50845b182c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]/div[5]/div/form</value>
      <webElementGuid>419a7395-a335-4198-ac41-8a700cd76c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>d4450e4c-bbe3-4440-8540-382c9f76bed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Current Filedependents.xlsxReplace WithBrowseNo file selectedAccepts up to 1MBComment * Required Cancel  Save ' or . = 'Current Filedependents.xlsxReplace WithBrowseNo file selectedAccepts up to 1MBComment * Required Cancel  Save ')]</value>
      <webElementGuid>d3197bf0-bfab-4fe8-a553-a08693c2a139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
